In [1]:
# Tool Setup

%load_ext tensorboard

import pathlib, os, sys, operator, re, datetime

from functools import reduce
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras import Model
import tensorflow_datasets as tfds
import h5py
import pandas as pd

# Use seaborn for pairplot.
# pip install -q seaborn

import seaborn as sns

# Make NumPy printouts easier to read.
np.set_printoptions(precision=3, suppress=True)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

%reload_ext tensorboard

print(tf.__version__)


2.19.0


## Creating Numpy Array of Training Data

In [64]:
data = 'p:\Mitchell\FFNeuralNetwork\statsTraining.csv'
dataAns = 'p:\Mitchell\FFNeuralNetwork\statsAnswer.csv'

raw_dataset = pd.read_csv(data, na_values='?', comment='\t', skipinitialspace=True)

dataset = raw_dataset.copy()
# dataset.tail()

dataset.isna().sum()                                                    # Counts number of Nan Values
dataset = dataset.dropna(axis = 0, subset = 'Previous Rank')            # Removes Nan Values from Previous Rank Rows
dataset = dataset.dropna(axis = 0, subset = 'Next Season Rank')         # Removes Nan Values from Next Season Rank Rows
dataset = dataset.fillna(0)                                             # Fills remaining Nan Values with 0
testSet = dataset.copy()                                                # Copying dataset to testset
dataset = dataset.drop('Next Season Rank', axis = 1)                    # Remove Rank column from training set
y = testSet[['Next Season Rank']]
print(dataset.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(dataset, y, test_size=0.2, random_state=42)

X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

(2368, 20)
(2368, 1)


# Creating Numpy Array of Test Data

In [ ]:
predictData = 'p:\Mitchell\FFNeuralNetwork\statsTesting.csv'

raw_test_dataset = pd.read_csv(predictData, na_values='?', comment='\t', skipinitialspace=True)

testDataSet = raw_test_dataset.copy()

testDataSet.isna().sum()                                                        # Counts number of Nan Values
testDataSet = testDataSet.dropna(axis = 0, subset = 'Previous Rank')            # Removes Nan Values from Previous Rank Rows
testDataSet = testDataSet.fillna(0)
names = testDataSet.copy()                                                      # Copying testDataSet to Names
testDataSet = testDataSet.drop('Player', axis = 1)                              # Remove Player column from test set    

PlayerNames = names['Player']

# print(PlayerNames.shape)
test = np.array(testDataSet)


(471,)


In [4]:

# regular = True 

# if(regular):
#     df = pd.read_csv(data)
#     df_y = pd.read_csv(dataAns)

#     numpy_array = df.to_numpy()
#     numpy_array = numpy_array[:, np.newaxis, :]
#     numpy_size = numpy_array.size

#     numpy_array_two = df_y.to_numpy()
#     numpy_array_two = numpy_array_two.astype(np.float32)

#     numpy_array[np.isnan(numpy_array)] = 0
#     numpy_array_test = numpy_array.astype(np.float32)

#     # print(numpy_array)
#     # print(numpy_size)
#     # print(numpy_array.shape)
#     # print(numpy_array_two.shape)
# else:
#     df = pd.read_csv(Smalldata)
#     df_y = pd.read_csv(SmalldataAns)

#     numpy_array = df.to_numpy()
#     numpy_array = numpy_array[:, np.newaxis, :]
#     numpy_size = numpy_array.size

#     numpy_array_two = df_y.to_numpy()
#     numpy_array_two = numpy_array_two.astype(np.float32)

#     numpy_array[np.isnan(numpy_array)] = 0
#     numpy_array_test = numpy_array.astype(np.float32)

#     # print(numpy_array)
#     # print(numpy_size)
#     # print(numpy_array.shape)
#     # print(numpy_array_two.shape) 

# H = numpy_array.shape[0]
# W = numpy_array.shape[1]

# H2 = numpy_array_two.shape[0]
# W2 = numpy_array_two.shape[1]

# numpy_array = numpy_array/100
# numpy_array_two = numpy_array_two

# print(numpy_array.shape)
# # print(numpy_array)   
# print(numpy_array_two)   

# # print(H)
# # print(W)

## Creating Numpy Array of Tesing Data

In [5]:
# Testdata = 'p:\Mitchell\FFNeuralNetwork\statsTesting.csv'
# TestdataAns = 'p:\Mitchell\FFNeuralNetwork\statsTestAnswer.csv'

# SmallTestdata = 'p:\Mitchell\FFNeuralNetwork\SmallBatchTest.csv'
# SmallTestdataAns = 'p:\Mitchell\FFNeuralNetwork\SmallBatchTestAns.csv'

# regular = True 

# if(regular):
#     Testdf = pd.read_csv(Testdata)
#     Testdf_y = pd.read_csv(TestdataAns)

#     numpy_array_test = Testdf.to_numpy()
#     numpy_array_test = numpy_array_test[:, np.newaxis, :]
#     numpy_sizeT = numpy_array_test.size

#     numpy_array_ans = Testdf_y.to_numpy()
#     numpy_array_ans = numpy_array_ans.astype(np.float32)

#     numpy_array_test[np.isnan(numpy_array_test)] = 0
#     numpy_array_test = numpy_array_test.astype(np.float32)
# else:
#     Testdf = pd.read_csv(SmallTestdata)
#     Testdf_y = pd.read_csv(SmallTestdataAns)

#     numpy_array_test = Testdf.to_numpy()
#     numpy_array_test = numpy_array_test[:, np.newaxis, :]
#     numpy_sizeT = numpy_array_test.size

#     numpy_array_ans = Testdf_y.to_numpy()
#     numpy_array_ans = numpy_array_ans.astype(np.float32)

#     numpy_array_test[np.isnan(numpy_array_test)] = 0
#     numpy_array_test = numpy_array_test.astype(np.float32)


# HT = numpy_array_test.shape[0]
# WT = numpy_array_test.shape[1]

# HT2 = numpy_array_ans.shape[0]
# WT2 = numpy_array_ans.shape[1]

# numpy_array_test = numpy_array_test/100
# numpy_array_ans = numpy_array_ans/(numpy_array_ans.size)
    
# print(numpy_array_test.shape)
# # print(numpy_array_test)
# # print(numpy_array_ans)

# # print(H)
# # print(W)


## Tensorflow Example

In [6]:
# mnist = tf.keras.datasets.mnist

# (x_train, y_train),(x_test, y_test) = mnist.load_data()
# x_train, x_test = x_train / 255.0, x_test / 255.0

# def create_model():
#   return tf.keras.models.Sequential([
#     tf.keras.layers.Input(shape=(28, 28), name='layers_input'),
#     tf.keras.layers.Flatten(name='layers_flatten'),
#     tf.keras.layers.Dense(512, activation='relu', name='layers_dense'),
#     tf.keras.layers.Dropout(0.2, name='layers_dropout'),
#     tf.keras.layers.Dense(10, activation='softmax', name='layers_dense_2')
#   ])

# model = create_model()
# model.compile(optimizer='adam',
#               loss='sparse_categorical_crossentropy',
#               metrics=['accuracy'])

# log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

# model.fit(x=x_train, 
#           y=y_train, 
#           epochs=5, 
#           validation_data=(x_test, y_test), 
#           callbacks=[tensorboard_callback])




## My Version

In [ ]:
model = tf.keras.models.Sequential([
  # tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(612, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(700, activation='softmax')
])

# model.compile(optimizer='adam',
#   loss='sparse_categorical_crossentropy',
#   metrics=['accuracy'])

model.compile(optimizer='adam',
  loss='mean_squared_error',
  metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

# print(numpy_array[1,0])
# model.fit(x_train, y_train, epochs=10)

model.fit(X_train, y_train, epochs=25, validation_data=(X_test, y_test), callbacks=[tensorboard_callback])
model.evaluate(X_test, y_test, verbose = 2)

# python -m tensorboard.main --logdir=logs/fit
# -------------------------------------------- Use above to view data


Epoch 1/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 4.9319e-04 - loss: 89175.6641 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 2/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 5.9625e-04 - loss: 84514.4375 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 3/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 7.9634e-04 - loss: 88827.1328 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 4/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 6.6868e-04 - loss: 85592.2500 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 5/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 6.4172e-04 - loss: 86759.5625 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 6/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0024 - loss: 87156.6562 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 7/100
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 2.0994e-04 - loss: 91514.5312 - val_accuracy: 0.0021 - val_loss: 96279.5625
Epoch 8/100
60/60 ━━━━━━━━━━━━━

[96279.5625, 0.002109704539179802]

## Single Test

In [66]:
players = np.array(PlayerNames)

player = []
finalPlayer = []

player.append(players)

for l in range(len(player)):
    finalPlayer.append(player[l])

# print(len(finalPlayer[0]))
print(finalPlayer[0][6])

Saquon Barkley


In [ ]:
guess = model.predict(test, verbose=0)

output = []

for i in range(len(guess)):
    val = 0
    num = 0
    for j in range(len(guess[i])):
        temp = guess[i][j]
        if(temp > val):
            val = float(temp)
            num = j
    output.append([num+1, finalPlayer[0][i]])

# print(output)
print(guess.shape)
prediction = pd.DataFrame(output)
prediction.to_excel('p:\Mitchell\FFNeuralNetwork\predictions.xlsx', index=False, sheet_name = "guesses")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(471, 700)
