In [1]:
# Tool Setup

%load_ext tensorboard

import pathlib, os, sys, operator, re, datetime

from functools import reduce
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras import Model
import tensorflow_datasets as tfds
import h5py
import pandas as pd

# Use seaborn for pairplot.
# pip install -q seaborn

import seaborn as sns

# Make NumPy printouts easier to read.
np.set_printoptions(precision=3, suppress=True)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

%reload_ext tensorboard

print(tf.__version__)


2.19.0


# Creating Numpy Array of Training Data

In [2]:
data = 'p:\Mitchell\FFNeuralNetwork\MATT.csv'

raw_dataset = pd.read_csv(data, na_values='?', comment='\t', skipinitialspace=True)

dataset = raw_dataset.copy()
# dataset.tail()

testSet = dataset.copy()                                                # Copying dataset to testset
dataset = dataset.drop('Pick', axis = 1)                    # Remove Rank column from training set
y = testSet[['Pick']]
print(dataset)
print(y.shape)
print(dataset.shape)

X_train, X_test, y_train, y_test = train_test_split(dataset, y, test_size=0.2, random_state=42)

X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

   Previous Pick  Round  Pick Num     RB     WR     QB     TE      K    DST  \
0            NaN    1.0       8.0  0.667  0.333  0.000  0.000  0.000  0.000   
1             WR    2.0      17.0  0.333  0.333  0.000  0.333  0.000  0.000   
2             RB    3.0      32.0  0.500  0.500  0.000  0.000  0.000  0.000   
3             WR    4.0      41.0  0.167  0.333  0.167  0.333  0.000  0.000   
4             TE    5.0      56.0  0.167  0.667  0.167  0.000  0.000  0.000   
..           ...    ...       ...    ...    ...    ...    ...    ...    ...   
93            WR   14.0     161.0  0.333  0.333  0.000  0.000  0.167  0.167   
94            RB   15.0     176.0  0.000  0.333  0.167  0.000  0.333  0.167   
95          D/ST   16.0     185.0  0.000  0.167  0.000  0.167  0.500  0.167   
96           NaN    NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN   
97           NaN    NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN   

    Previous Rank   Age  
0            75.0  27.0  

# Creating Numpy Array of Test Data

# Creating Numpy Array of Tesing Data

## My Version

In [68]:
model = tf.keras.models.Sequential([
  # tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(6, activation='softmax')
])

model.compile(optimizer='adam',
  loss='sparse_categorical_crossentropy',
  metrics=['accuracy'])

# model.compile(optimizer='adam',
#   loss='mean_squared_error',
#   metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

# print(numpy_array[1,0])
# model.fit(x_train, y_train, epochs=10)

model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), callbacks=[tensorboard_callback])
# model.evaluate(X_test, y_test, verbose = 2)

# python -m tensorboard.main --logdir=logs/fit
# -------------------------------------------- Use above to view data

Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 128ms/step - accuracy: 0.1205 - loss: 2.3771 - val_accuracy: 0.3000 - val_loss: 1.7922
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.2434 - loss: 2.0003 - val_accuracy: 0.3500 - val_loss: 1.6806
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.2185 - loss: 1.8372 - val_accuracy: 0.4500 - val_loss: 1.6798
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.3363 - loss: 1.8441 - val_accuracy: 0.2500 - val_loss: 1.7171
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3312 - loss: 1.7939 - val_accuracy: 0.2500 - val_loss: 1.7534
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3115 - loss: 1.7554 - val_accuracy: 0.2500 - val_loss: 1.7688
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2422 - loss: 1.8280 - val_accuracy: 0.2500 - val_loss: 1.7403
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.3195 - loss: 1.7855 - val_accuracy: 0.2500 - val_loss: 1.7134

## Single Test

In [64]:
indata = np.empty((1, 2))
indata.fill(1)
print(indata)

guess = model.predict(dataset, verbose=0)

# print(output)
print(guess.shape)
print(guess)

[[1. 1.]]
(96, 6)
[[0.164 0.193 0.171 0.166 0.159 0.147]
 [0.296 0.268 0.112 0.104 0.117 0.104]
 [0.217 0.234 0.147 0.13  0.166 0.107]
 [0.299 0.261 0.115 0.104 0.137 0.083]
 [0.458 0.31  0.056 0.053 0.082 0.041]
 [0.231 0.255 0.143 0.134 0.169 0.068]
 [0.221 0.271 0.129 0.143 0.176 0.06 ]
 [0.267 0.3   0.14  0.094 0.15  0.049]
 [0.211 0.301 0.147 0.134 0.164 0.043]
 [0.272 0.321 0.131 0.097 0.144 0.035]
 [0.362 0.335 0.096 0.064 0.117 0.026]
 [0.257 0.356 0.129 0.089 0.144 0.025]
 [0.204 0.35  0.108 0.148 0.168 0.022]
 [0.252 0.383 0.11  0.093 0.144 0.018]
 [0.198 0.386 0.109 0.132 0.16  0.015]
 [0.444 0.378 0.06  0.03  0.078 0.01 ]
 [0.164 0.193 0.171 0.166 0.159 0.147]
 [0.225 0.23  0.14  0.133 0.147 0.125]
 [0.293 0.27  0.116 0.099 0.13  0.092]
 [0.227 0.241 0.139 0.137 0.16  0.095]
 [0.231 0.242 0.131 0.139 0.177 0.08 ]
 [0.297 0.265 0.127 0.097 0.15  0.064]
 [0.366 0.291 0.09  0.073 0.132 0.049]
 [0.267 0.3   0.14  0.094 0.15  0.049]
 [0.211 0.301 0.147 0.134 0.164 0.043]
 [0.417